# manual_insert_config.yaml

# Video insertions - insert multiple videos at specific times
video_inserts:
  # Insert at 5 seconds into main video
  - time: "00:05.00"              # When to insert in main video
    videos:
      # First video clip (top-left corner)
      - source: "outputs/videos/172528_AI+robot_large.mp4"
        start: "00:00.00"          # Start time in source video
        duration: "00:20.00"       # How long to insert
        position: "78%,50%"       # Position on screen
        size: "40%"               # Size as percentage of main video width
        loop: true                # Loop if source is shorter than duration

  # Insert at 15 seconds
  - time: "00:15.00"
    videos:
      - source: "outputs/videos/183107_AI+robot_large.mp4"
        start: "00:00.00"
        duration: "00:20.00"
        position: "78%,50%"       # Position on screen
        size: "40%" 
        loop: true

# Audio insertions - add audio overlays (optional)
audio_inserts:
  # Background music overlay
  - time: "00:00.00"              # When to start audio in main video
    source: "outputs/tts/script/script.wav"
    start: "00:00.00"             # Start time in source audio
    duration: "00:50.00"          # How long to play
    volume: 0.9               # Volume level (0.0 to 1.0+)
    mix_mode: "replace"           # "overlay" (mix) or "replace"