# Memory-efficient configuration for large videos (4K)
# Optimized for HPC environments with limited GPU memory

video_inserts:
  # Test with a single small overlay to verify memory efficiency
  - time: "00:00.05"  # Insert very early to test quickly
    videos:
      - source: "outputs/videos/172894_finance_large.mp4"
        start: "00:03.00"
        duration: "00:03.00"  # Shorter duration to reduce memory usage
        position: "75%,50%"   # Center-based coordinates
        size: "46%"           # Size as specified in user's command
        loop: false

# Configuration for memory optimization
processing_settings:
  batch_size: 5             # Very small batch size for 4K videos
  memory_efficient: true    # Enable memory-efficient processing
  gpu_memory_fraction: 0.6  # Conservative GPU memory usage

# Note: This configuration is optimized for very large videos (4K)
# - Uses smaller batch sizes to prevent GPU memory overflow
# - Enables chunked processing for overlay operations
# - Includes memory monitoring and cleanup between operations
